name: Generate SVG

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Stats
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: yarn

      - name: Build JS
        run: yarn build

      - name: Generate SVG
        run: LEETCODE_USERNAME=${{ secrets.xQula }} yarn start

      - name: Commit to the repo
        run: |
          git config --global user.name "knlnks/leetcode-stats"
          git config --global user.email "soulkks@hotmail.ca"
          git add .
          # "echo" returns true so the build succeeds, even if no changed files
          git commit -m '🎉 Update Generated Files' || echo
          git push
